### ISSUE TITLE
[ Request ] zte b860h v2.1

### ISSUE THREAD

**Issue by hostkit** [ndunks/custom-rom-stb-zte-B860-indihome#1]
Gan apa ini juga support pada versi 2.1? 
Aplikasi ini berjalan di Windows juga?

**Comment by ndunks** [comment]
bedanya apa gan untuk v2.1? kalo chipsetnya masih sama (Processor AMLogic) harusnya si bisa..
Untuk ngedit oprekannya blm support di windows, bakal mayan lemot juga karena GIT sendiri juga rada lemot di Windows. Mending dual boot/virtual pake linux..
Kalo cuman mau ngeflash room yg udah jadi si bisa pake windows, cuma beda command dikit

**Comment by ndunks** [comment]
apa firmware 2.1 maksudnya yang locked bootloader dan tidak bisa masuk USB Burn mode? cek di folder [firmware-bejat](../tree/master/firmware-bejat) mas

**Comment by hostkit** [comment]
> apa firmware 2.1 maksudnya yang locked bootloader dan tidak bisa masuk USB Burn mode? cek di folder [firmware-bejat](../tree/master/firmware-bejat) mas

Bukan, kalo soc nya amlogic s950x-bv, ram 2gb, untuk detail lain tidak begitu paham.

Saya sudah coba install gapps manual juga fc

**Comment by ndunks** [comment]
mod rom ini belum bisa GAPPS,, tapi bisa utk semua STB merah 4k
`s950x` --> Microprocessor

bisa utk board: 
- GXL p212 1g
- GXL p212 2g
- GXL p215 1g
 
pake u-boot HGxxx

**Comment by hostkit** [comment]
Kalau launcher dan maincontrol dihapus trus pakai apa gan buat setting nya? Kayaknya gak ada app setting yg agan upload

**Comment by hostkit** [comment]
> mod rom ini belum bisa GAPPS,, tapi bisa utk semua STB merah 4k
> `s950x` --> Microprocessor
> 
> bisa utk board:
> 
> * GXL p212 1g
> * GXL p212 2g
> * GXL p215 1g
> 
> pake u-boot HGxxx

Berarti untuk gapps.sh masih belum berfungsi/masih bekerja dibeberapa stb saja

**Comment by ndunks** [comment]
> Kalau launcher dan maincontrol dihapus trus pakai apa gan buat setting nya? Kayaknya gak ada app setting yg agan upload

iya udah coba setting bawaan android tapi belum nemu yang work. itu saya bikin APK Custom sendiri (`klampok.apk`) untuk nge-launch setting bawaan ZTEnya plus bisa fungsi Toast utk dipanggil dari shell
